apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: krampoline
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_a9e11c0e3efd:latest
          env:
            - name: DB_HOST
              value: mysql.krampoline.svc.cluster.local
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: database-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: root-password
            - name: DB_PORT
              value: "3306"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: secret
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: krampoline
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080