apiVersion: kustomize.config.k8s.io/v1beta1  # 잘못된 apiVersion 수정
kind: Kustomization
namespace: krampoline
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - Mysql.yaml
  - server-secret.yaml