apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: krampoline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: krampoline
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "!db1234"
            - name: MYSQL_PASSWORD
              value: "!als1234"
            - name: MYSQL_DATABASE
              value: als_ide_db
            - name: MYSQL_USER
              value: user
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: krampoline
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql